### ISSUE TITLE
Add support for routes

### ISSUE THREAD

**Issue by bartv** [inmanta/nfv-test-api#2]
The API should expose an endpoint that allows to :
- get the current routing table
- add routes with an IP as next hop. For example (using ip -j keys), dst: 172.16.64.0/18, gateway: 172.17.0.1

For the default route, ip ro ls will return the value "default" instead of "0.0.0.0/0". It think the latter is actually better for the API because it is also a valid ipv4 network address and "default" is not.

**Comment by andraskvr** [comment]
@bartv  Could you add some description to this?

**Comment by bartv** [comment]
@andraskvr done. Missed that one.
