### ISSUE TITLE
Add support for bonding

### ISSUE THREAD

**Issue by bartv** [inmanta/nfv-test-api#40]
The goal of this ticket is to

- create an API endpoints that supports the creation of a bond interfaces that has a list of slave interfaces
- and endpoint that allows to fetch the status of the bond and the individual slaves. Returning the content of `/proc/net/bonding/bond0` (or other name of course) is probably sufficient. 
- Make sure that the subif and ip address calls work with a bond

This article contains useful commands that the service should use: http://www.uni-koeln.de/~pbogusze/posts/LACP_configuration_using_iproute2.html

**Comment by edvgui** [comment]
Support added in https://github.com/inmanta/nfv-test-api/pull/23
Test case added in https://github.com/inmanta/nfv-test-api/pull/42
